logging:
  config: classpath:logback.xml
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.10.2:3307/dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: "boarduser"
    password: "dIWPEX7#4x5l"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update # validate
security:
  key: "jixgmcnvnxbhggugishotrqqnqtamypqtyxbruxkodbuethkpjekmudutodswpymmftpjkvpdumdqsayxqtoqokqcvpnogoefwyptgeaiulodthvwomouqmgednlumbvrverjetswqakbjxuznzkckiwsnuqowdnujojdblliggivbhtlhpzkvnjznifgqsukomajkvgmxjelodtcaisrwcpixzednpkfepgacadgaewujrvrpqrwhvjpjtimhtgemkeqdvaupujhrqmmbdkxfofoossmkqftczvfoflsthacedsxvrxhkxwfcccuztsjzvitmigbbillilrmxlzfaypumjwhoozfrkpxjpghxpqxzwvterkepybppvkoftpuqkdxzvoigznhfyjejjctxtbnznayxnhstvwhfvsfbgmhizvgwqfvcsduucbitwerlwmqlrbdzyyhwxuoakhyhfmvbclywovbbddqskmtzepioqtwfokhrojrmmhpytl"
  token-expire-minute: 1